name: PY Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name 
  # schedule:
  #   # - cron: "*/5 * * * *"
  #   - cron: '0 */6 * * *'

permissions:
  contents: read
env:
  mc_sec  : ${{ secrets.MC_SEC }}
  AUDIO_HOOK : ${{ secrets.AUDIO_HOOK }}

  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
  
      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install dependencies
        working-directory: ./py 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Install ffmpeg
      #   run: 
      #     sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Deploy Check
        run: |
          python py/audio_scraper.py


          
