name: PY Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name 
  # schedule:
  #   # - cron: "*/5 * * * *"
  #   - cron: '0 */6 * * *'

permissions:
  contents: read
env:
  mc_sec  : ${{ secrets.MC_SEC }}

  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install dependencies
        working-directory: ./py 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ffmpeg
        run: 
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install -r requirements.txt

      - name: Deploy Check
        run: |
          python py/nlp.py
