name: PY Tests

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main  # Change this to your main branch name 
# - cron: '0 */2 * * *'
on:
  push:
    branches:
      - main  # Change this to your main branch name 
  schedule:
    - cron: '0 */2 * * *'
#    - cron: "*/1 * * * *"
      
permissions:
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./py 

    - name: Deploy Check
      run: |
        python py/nlp.py
